Autogenerate latex

diff --git a/benchmark b/benchmark
--- a/benchmark
+++ b/benchmark
@@ -8,21 +8,13 @@ echo
 
 read -rp "Option: " user_input
 
-_generate_latex_report()
-{
-  local output_path=output/latex
-  mkdir -vp $output_path
-
-  pdflatex -interaction=nonstopmode -output-directory=$output_path base.tex
-}
-
 if [ "$user_input" == "1" ]; then
-    python3 commands/subcommand_run_benchmarks.py
+  python3 commands/subcommand_run_benchmarks.py
 elif [ "$user_input" == "2" ]; then
-    python3 commands/subcommand_plot_normal_distributions.py
+  python3 commands/subcommand_plot_normal_distributions.py
 elif [ "$user_input" == "3" ]; then
-    _generate_latex_report
+  python3 commands/subcommand_generate_latex.py
 else
-    echo "Invalid input. Enter an option between 1 and 3. Exiting with error."
-    exit 1
+  echo "Invalid input. Enter an option between 1 and 3. Exiting with error."
+  exit 1
 fi
